name: connect_four
description: Mobile game consisting of connecting four dots to make a square

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
  bloc: ^6.1.1
  flutter_bloc: ^6.1.1
  equatable: ^1.0.0
  flutter_material_pickers: ^1.9.0
  game_manager:
    path: game_manager
  shared_preferences: ^0.5.12+4
  rxdart: ^0.22.0
  font_awesome_flutter: ^8.4.0
  flutter_countdown_timer: ^3.0.0
  circular_countdown_timer: ^0.0.9
  simple_animations: ^2.2.3
  flutter_staggered_animations: "^0.1.2"
  audioplayers: ^0.17.3
  flutter_custom_dialog: ^1.0.20
  tutorial_coach_mark: ^0.6.0+1
  firebase_admob: ^0.11.0+1
  logging: ^0.11.4
  share: ^0.6.5+4
  confetti: ^0.5.4+1
  easy_localization: 2.3.3+1
  easy_localization_loader: 0.0.2
  country_icons: ^1.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  #flutter_test:
  #  sdk: flutter
  #integration_test:
  #  sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/screenshots/
    - assets/background/
    - assets/img/
    - assets/fonts/
    - assets/sounds/bgm/
    - assets/sounds/sfx/
    - assets/translations/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Tsa
       fonts:
         - asset: assets/fonts/Tsa-XLJo.ttf
     - family: Squirk
       fonts:
         - asset: assets/fonts/Squirk-RMvV.ttf
     - family: BigSpace
       fonts:
         - asset: assets/fonts/BigSpace-rPKx.ttf
     - family: FrostbiteBossFight
       fonts:
         - asset: assets/fonts/FrostbiteBossFight-dL0Z.ttf
     - family: Robus
       fonts:
         - asset: assets/fonts/Robus-BWqOd.otf
     - family: SlemanDemo
       fonts:
         - asset: assets/fonts/SlemanDemo-1Gaz4.ttf
     - family: SportypoReguler
       fonts:
         - asset: assets/fonts/SportypoReguler-OVGwe.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
